name: Build and Update Project

on:
  push:
    branches:
      - main

jobs:
  build_and_update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm run build

    - name: Update Project (Replace with your update command)
      run: |
        cd /var/www/gctrade/gctrade-front &&
        git pull

    # - name: Deploy (Replace with your deploy command)
    #   run: |
    #     # Add your deploy command here, e.g., restarting a service
    #     pm2 restart your_service_name
