on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: self-hosted
    
    steps:
    - name: connect and pull
      working-directory: ${{ secrets.WORK_DIR }}
      run: | 
          cd /var/www/gctrade/gctrade-front &&
          git checkout ${{ secrets.MAIN_BRANCH }} &&
          git pull &&
          yarn &&
          yarn build &&
          pm2 start
